"""
Exemplo 1.
Explicação do nível do log default

A BIBLIOTECA LOGGING POSSUI COMO DEFAULT, OS SEGUINTES LOG LEVELS:

DEBUG - INFORMAÇÕES MAIS DETALHADAS, QUANDO ESTAMOS BUSCANDO PROBLEMAS
INFO - CONFIRMAR QUE AS COISAS ESTÃO FUNCIONANDO COMO ESPERADO
WARNING - INFORMAÇÃO DE QUE ALGO INESPERADO ACONTECEU (MAS TUDO FUNCIONA BEM)
ERROR - QUANDO ALGO INESPERADO OCORRE E O PROGRAMA NÃO CONSEGUE EXECUTAR ALGO
CRITICAL - UM ERRO GRAVE QUE IMPEDIU O SISTEMA DE EXECUTAR ALGO

"""

import logging

logging.debug('debug')
logging.info('info')
logging.warning('warning')