"""
Exemplo 2.
Como escrever o log em um arquivo

A BIBLIOTECA LOGGING POSSUI COMO DEFAULT, OS SEGUINTES LOG LEVELS:

DEBUG - INFORMAÇÕES MAIS DETALHADAS, QUANDO ESTAMOS BUSCANDO PROBLEMAS
INFO - CONFIRMAR QUE AS COISAS ESTÃO FUNCIONANDO COMO ESPERADO
WARNING - INFORMAÇÃO DE QUE ALGO INESPERADO ACONTECEU (MAS TUDO FUNCIONA BEM)
ERROR - QUANDO ALGO INESPERADO OCORRE E O PROGRAMA NÃO CONSEGUE EXECUTAR ALGO
CRITICAL - UM ERRO GRAVE QUE IMPEDIU O SISTEMA DE EXECUTAR ALGO

"""

import logging

logging.basicConfig(filename='exemplo_2.log', level=logging.DEBUG, filemode='w')

logging.info('OLÁ ESTAMOS NO ARQUIVO')
logging.debug('debug')
logging.info('info')
logging.warning('warning')